name: CI/CD for customer_order_services django api

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  

    - name: Set up Python
      uses: actions/setup-python@v4  
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage  # Install coverage for code coverage

    - name: Run Unit Tests with Coverage
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}  
      run: |
        coverage run --source='.' manage.py test  # Run tests with coverage
        coverage report  # Display coverage report
        coverage html  # Generate HTML report for coverage

    - name: Collect Static Files
      run: |
        python manage.py collectstatic --noinput

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}  
      run: |
        curl -X POST https://api.render.com/deploy \
        -H "Authorization: Bearer $RENDER_API_KEY" \
        -d '{"serviceId":"srv-crpr70t6l47c73ao44r0"}'
